# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\Work\Code\greenyy\uisrc\dialog\ruleItemSelect.ui'
#
# Created by: PySide6 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_RuleItemDialog(object):
    def setupUi(self, RuleItemDialog):
        RuleItemDialog.setObjectName("RuleItemDialog")
        RuleItemDialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(RuleItemDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lblParent = QtWidgets.QLabel(RuleItemDialog)
        self.lblParent.setObjectName("lblParent")
        self.gridLayout.addWidget(self.lblParent, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(RuleItemDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(RuleItemDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.treeElementSelect = QtWidgets.QTreeWidget(RuleItemDialog)
        self.treeElementSelect.setObjectName("treeElementSelect")
        self.gridLayout.addWidget(self.treeElementSelect, 1, 0, 1, 2)

        self.retranslateUi(RuleItemDialog)
        self.buttonBox.accepted.connect(RuleItemDialog.accept)
        self.buttonBox.rejected.connect(RuleItemDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RuleItemDialog)

    def retranslateUi(self, RuleItemDialog):
        _translate = QtCore.QCoreApplication.translate
        RuleItemDialog.setWindowTitle(_translate("RuleItemDialog", "Добавить"))
        self.lblParent.setText(_translate("RuleItemDialog", "null"))
        self.label.setText(_translate("RuleItemDialog", "Относится к:"))
        self.treeElementSelect.headerItem().setText(0, _translate("RuleItemDialog", "Элемент"))
