# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\Work\Code\Greenyy\uisrc\ruleItemSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui import UiDefinition


class Ui_RuleItemAppendDialog(UiDefinition):
    def setupUi(self, RuleItemAppendDialog):
        RuleItemAppendDialog.setObjectName("RuleItemAppendDialog")
        RuleItemAppendDialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(RuleItemAppendDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lblParent = QtWidgets.QLabel(RuleItemAppendDialog)
        self.lblParent.setObjectName("lblParent")
        self.gridLayout.addWidget(self.lblParent, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(RuleItemAppendDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(RuleItemAppendDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.treeElementSelect = QtWidgets.QTreeWidget(RuleItemAppendDialog)
        self.treeElementSelect.setObjectName("treeElementSelect")
        self.gridLayout.addWidget(self.treeElementSelect, 1, 0, 1, 2)

        self.retranslateUi(RuleItemAppendDialog)
        self.buttonBox.accepted.connect(RuleItemAppendDialog.accept)
        self.buttonBox.rejected.connect(RuleItemAppendDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RuleItemAppendDialog)

    def retranslateUi(self, RuleItemAppendDialog):
        _translate = QtCore.QCoreApplication.translate
        RuleItemAppendDialog.setWindowTitle(_translate("RuleItemAppendDialog", "Добавить"))
        self.lblParent.setText(_translate("RuleItemAppendDialog", "null"))
        self.label.setText(_translate("RuleItemAppendDialog", "Относится к:"))
        self.treeElementSelect.headerItem().setText(0, _translate("RuleItemAppendDialog", "Элемент"))
