# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uisrc\rule.ui'
#
# Created by: PySide6 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

class Ui_RulePropertiesDialog(object):
    def setupUi(self, RulePropertiesDialog):
        RulePropertiesDialog.setObjectName("RulePropertiesDialog")
        RulePropertiesDialog.resize(400, 550)
        RulePropertiesDialog.setMinimumSize(QtCore.QSize(400, 550))
        self.gridLayout = QtWidgets.QGridLayout(RulePropertiesDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.treeRuleLogic = QtWidgets.QTreeWidget(RulePropertiesDialog)
        self.treeRuleLogic.setObjectName("treeRuleLogic")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeRuleLogic)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeRuleLogic)
        self.gridLayout.addWidget(self.treeRuleLogic, 6, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(RulePropertiesDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.pteRuleDesc = QtWidgets.QPlainTextEdit(RulePropertiesDialog)
        self.pteRuleDesc.setMaximumSize(QtCore.QSize(16777215, 81))
        self.pteRuleDesc.setObjectName("pteRuleDesc")
        self.gridLayout.addWidget(self.pteRuleDesc, 4, 0, 1, 2)
        self.lneRuleName = QtWidgets.QLineEdit(RulePropertiesDialog)
        self.lneRuleName.setObjectName("lneRuleName")
        self.gridLayout.addWidget(self.lneRuleName, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddTrigger = QtWidgets.QPushButton(RulePropertiesDialog)
        self.btnAddTrigger.setObjectName("btnAddTrigger")
        self.horizontalLayout.addWidget(self.btnAddTrigger)
        self.btnAddAction = QtWidgets.QPushButton(RulePropertiesDialog)
        self.btnAddAction.setObjectName("btnAddAction")
        self.horizontalLayout.addWidget(self.btnAddAction)
        self.gridLayout.addLayout(self.horizontalLayout, 12, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(RulePropertiesDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 2)
        self.btnStatus = QtWidgets.QPushButton(RulePropertiesDialog)
        self.btnStatus.setObjectName("btnStatus")
        self.gridLayout.addWidget(self.btnStatus, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(RulePropertiesDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(RulePropertiesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 16, 0, 1, 2)
        self.label = QtWidgets.QLabel(RulePropertiesDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(RulePropertiesDialog)
        self.buttonBox.accepted.connect(RulePropertiesDialog.accept)
        self.buttonBox.rejected.connect(RulePropertiesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RulePropertiesDialog)

    def retranslateUi(self, RulePropertiesDialog):
        _translate = QtCore.QCoreApplication.translate
        RulePropertiesDialog.setWindowTitle(_translate("RulePropertiesDialog", "Правило"))
        self.treeRuleLogic.headerItem().setText(0, _translate("RulePropertiesDialog", "Логика"))
        self.treeRuleLogic.headerItem().setText(1, _translate("RulePropertiesDialog", "Источник"))
        self.treeRuleLogic.headerItem().setText(2, _translate("RulePropertiesDialog", "Содержимое"))
        __sortingEnabled = self.treeRuleLogic.isSortingEnabled()
        self.treeRuleLogic.setSortingEnabled(False)
        self.treeRuleLogic.topLevelItem(0).setText(0, _translate("RulePropertiesDialog", "Условия"))
        self.treeRuleLogic.topLevelItem(1).setText(0, _translate("RulePropertiesDialog", "Действия"))
        self.treeRuleLogic.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("RulePropertiesDialog", "Статус:"))
        self.pteRuleDesc.setPlaceholderText(_translate("RulePropertiesDialog", "Описание правила..."))
        self.lneRuleName.setPlaceholderText(_translate("RulePropertiesDialog", "Имя правила..."))
        self.btnAddTrigger.setText(_translate("RulePropertiesDialog", "Добавить условие..."))
        self.btnAddAction.setText(_translate("RulePropertiesDialog", "Добавить действие..."))
        self.label_4.setText(_translate("RulePropertiesDialog", "Логика:"))
        self.btnStatus.setText(_translate("RulePropertiesDialog", "Активно"))
        self.label_3.setText(_translate("RulePropertiesDialog", "Описание (необязательно):"))
        self.label.setText(_translate("RulePropertiesDialog", "Имя правила:"))


class Rules(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()

        self.ui = Ui_RulePropertiesDialog()
        self.ui.setupUi(self)
