# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\Work\Code\grassyy\uisrc\window\general.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneralWindow(object):
    def setupUi(self, GeneralWindow: QtWidgets.QMainWindow):
        GeneralWindow.setObjectName("GeneralWindow")
        GeneralWindow.resize(600, 600)
        GeneralWindow.setMinimumSize(QtCore.QSize(600, 600))
        self.mdi = QtWidgets.QMdiArea(GeneralWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdi.sizePolicy().hasHeightForWidth())
        self.mdi.setSizePolicy(sizePolicy)
        self.mdi.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdi.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdi.setActivationOrder(QtWidgets.QMdiArea.ActivationHistoryOrder)
        self.mdi.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.mdi.setObjectName("mdi")
        GeneralWindow.setCentralWidget(self.mdi)
        self.menubar = QtWidgets.QMenuBar(GeneralWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        self.meiPlants = QtWidgets.QMenu(self.menubar)
        self.meiPlants.setObjectName("meiPlants")
        self.meiSettings = QtWidgets.QMenu(self.menubar)
        self.meiSettings.setObjectName("meiSettings")
        GeneralWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GeneralWindow)
        self.statusbar.setObjectName("statusbar")
        GeneralWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(GeneralWindow)
        self.action.setObjectName("action")
        self.meiDevices = QtWidgets.QAction(GeneralWindow)
        self.meiDevices.setObjectName("meiDevices")
        self.meiRules = QtWidgets.QAction(GeneralWindow)
        self.meiRules.setObjectName("meiRules")
        self.meiLog = QtWidgets.QAction(GeneralWindow)
        self.meiLog.setObjectName("meiLog")
        self.meiSettings.addAction(self.meiDevices)
        self.meiSettings.addAction(self.meiRules)
        self.meiSettings.addAction(self.meiLog)
        self.menubar.addAction(self.meiPlants.menuAction())
        self.menubar.addAction(self.meiSettings.menuAction())

        self.retranslateUi(GeneralWindow)
        QtCore.QMetaObject.connectSlotsByName(GeneralWindow)

    def retranslateUi(self, GeneralWindow):
        _translate = QtCore.QCoreApplication.translate
        GeneralWindow.setWindowTitle(_translate("GeneralWindow", "Иваров листочек"))
        self.meiPlants.setTitle(_translate("GeneralWindow", "Грядка"))
        self.meiSettings.setTitle(_translate("GeneralWindow", "Настройки"))
        self.action.setText(_translate("GeneralWindow", "Устройства..."))
        self.meiDevices.setText(_translate("GeneralWindow", "Устройства..."))
        self.meiRules.setText(_translate("GeneralWindow", "Правила..."))
        self.meiLog.setText(_translate("GeneralWindow", "Журнал..."))
